# Generated by Django 4.2.7 on 2023-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='recommended_for_publication',
            new_name='approved_pres',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='recommended_for_publication',
            new_name='approved_reg',
        ),
        migrations.AddField(
            model_name='author',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
