# Generated by Django 4.2.7 on 2023-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conferences_app', '0002_rename_recommended_for_publication_presentation_approved_pres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='groups',
            field=models.ManyToManyField(related_name='author_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_permissions',
            field=models.ManyToManyField(related_name='author_user_permissions', to='auth.permission'),
        ),
    ]
