# Generated by Django 4.2.7 on 2023-12-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('edition_index', models.CharField(max_length=50)),
                ('editor_last_name', models.CharField(max_length=255)),
                ('editor_first_name', models.CharField(max_length=255)),
                ('editor_middle_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_postoffice_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.IntegerField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper')),
                ('printing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.printinghouse')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.postoffice')),
            ],
        ),
    ]
