site_name: My Docs
theme:
    name: dracula
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - home: index.md
  - lab 1:
    - task 1: lab1/task1.md
    - task 2: lab1/task2.md
    - task 3: lab1/task3.md
    - task 4: lab1/task4.md
    - task 5: lab1/task5.md
  - lab 2:
    - admin: lab2/admin.md
    - forms: lab2/forms.md
    - model: lab2/models.md
    - settings: lab2/settings.md
    - templates: lab2/templates.md
    - views: lab2/views.md
    - urls: lab2/urls.md